- id: spotless_apply
  name: Spotless apply (Java)
  entry: java/spotless_apply.py
  language: script
  description: "Detecta Maven/Gradle e executa 'spotless:apply' / 'spotlessApply'."
  files: \.(java|xml|gradle|kts)$

- id: test
  name: Run project tests (Maven/Gradle)
  entry: java/run_tests.py
  language: script
  args: ["--task", "test"]
  description: "Detecta Maven/Gradle e roda os testes (mvn test / gradle test)."
  files: \.(java|xml|gradle|kts)$